name: Test

on:
    pull_request:
    workflow_dispatch:

jobs:
    pip-audit:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.11
            - run: |
                  pip install pip-audit
                  pip-audit . --progress-spinner off

    tox:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        strategy:
            matrix:
                version: [3.10, 3.11, 3.12, 3.13]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.version }}
            - run: |
                  pip install .[dev]
                  tox -q
