name: Test

on:
    pull_request:
    workflow_dispatch:

jobs:
    backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.11
            - run: |
                  pip install pip-audit
                  pip-audit . --progress-spinner off
