name: VULNOW Test

on:
    push:
        branches: [ 'test/vulnow' ]

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            -   name: "VULNOW :: Get SBOM"
                run: |
                    docker run -e VULNOW_API_KEY=${{ secrets.VULNOW_API_KEY }} \
                      -e ORG=$ORG \
                      -e REPO=$REPO \
                      -e GITHUB_EVENT_NAME \
                      -e GITHUB_HEAD_REF \
                      -e GITHUB_BASE_REF \
                      -e GITHUB_REF_NAME \
                      -e GITHUB_REF \
                      -v ${{ github.workspace }}:/repo --workdir /repo \
                      $VULNOW_IMG \
                      python /app/cicd_cli.py get-sbom .
                env:
                    VULNOW_API_KEY: ${{ secrets.VULNOW_API_KEY }}

            -   name: "VULNOW :: Send SBOM"
                run: |
                    cat dynamic_traits.yml
                    docker run -e VULNOW_API_KEY=${{ secrets.VULNOW_API_KEY }} \
                      -e ORG=$ORG \
                      -e REPO=$REPO \
                      -e GITHUB_EVENT_NAME \
                      -e GITHUB_HEAD_REF \
                      -e GITHUB_BASE_REF \
                      -e GITHUB_REF_NAME \
                      -e GITHUB_REF \
                      -v ${{ github.workspace }}:/repo --workdir /repo \
                      $VULNOW_IMG \
                      python /app/cicd_cli.py send-bom --api_url $VULNOW_ENDPOINT -f bom.json --bom_type sbom
                env:
                    VULNOW_API_KEY: ${{ secrets.VULNOW_API_KEY }}
