name: VULNOW Test

on:
    push:
        branches: [ 'test/vulnow_multirepo' ]
    workflow_dispatch:


jobs:
  set-build-started-at:
    runs-on: ubuntu-latest
    outputs:
      build_started_at: ${{ steps.set-timestamp.outputs.build_started_at }}
    steps:
      - name: Set BUILD_STARTED_AT
        id: set-timestamp
        shell: bash
        run: |
          BUILD_STARTED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "build_started_at=$BUILD_STARTED_AT" >> $GITHUB_OUTPUT

  build:
    needs: set-build-started-at
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - backend
          - frontend
    env:
      BUILD_STARTED_AT: ${{ needs.set-build-started-at.outputs.build_started_at }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
        if: matrix.app == 'backend'

      - run: |
          pip install build
          python -m build
        working-directory: ./backend
        if: matrix.app == 'backend'

      - name: "VULNOW :: Setup Variables"
        id: vars
        run: |
          ORG=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          REPO=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          COMMITID=$(git rev-parse HEAD)
          # Export these values to the environment
          echo "ORG=$ORG" >> $GITHUB_ENV
          echo "REPO=$REPO" >> $GITHUB_ENV
          echo "COMMITID=$COMMITID" >> $GITHUB_ENV
          echo "BUILD_STARTED_AT=${{ env.BUILD_STARTED_AT }}" >> $GITHUB_ENV
          # Set VULNOW variables directly
          echo "VULNOW_ENDPOINT=https://customer1-1d131cf0.vulnow.io/api/dataingestion" >> $GITHUB_ENV
          echo "VULNOW_IMG=drakkars/vulnow:0.4.3" >> $GITHUB_ENV
          # Set application-specific variables
          echo "APPLICATION_PATH=${{ matrix.app }}" >> $GITHUB_ENV


      - name: "VULNOW :: Get and send SBOM"
        run: |
          docker run -e VULNOW_API_KEY=${{ secrets.VULNOW_API_KEY }} \
            -e ORG=$ORG \
            -e REPO=$REPO \
            -e APPLICATION_PATH=$APPLICATION_PATH \
            -e GITHUB_EVENT_NAME \
            -e GITHUB_HEAD_REF \
            -e GITHUB_BASE_REF \
            -e GITHUB_REF_NAME \
            -e GITHUB_REF \
            -e BUILD_STARTED_AT=$BUILD_STARTED_AT \
            -v ${{ github.workspace }}:/repo --workdir /repo \
            $VULNOW_IMG \
            python /app/cicd_cli.py get-and-send-bom . --application-path $APPLICATION_PATH --api_url $VULNOW_ENDPOINT -f bom.json --bom_type sbom
        env:
          VULNOW_API_KEY: ${{ secrets.VULNOW_API_KEY }}

      - name: "VULNOW :: Ingest"
        run: |
          cat $APPLICATION_PATH/dynamic_traits.yml
          docker run -e VULNOW_API_KEY=${{ secrets.VULNOW_API_KEY }} \
            -v ${{ github.workspace }}:/repo --workdir /repo \
            $VULNOW_IMG \
            python /app/cicd_cli.py ingest --api_url $VULNOW_ENDPOINT --application-path $APPLICATION_PATH
        env:
          VULNOW_API_KEY: ${{ secrets.VULNOW_API_KEY }}
